### ISSUE TITLE
[0.8] x-repeat failing to stamp instances on safari

### ISSUE THREAD

**Issue by tjsavage** [PolymerElements/test-fixture#8] opened 2015-05-22 17:34 UTC
I've gone pretty far down the rabbit hole, but I think it's time to pass off to you @kevinpschaaf 

To see the weirdness:
* Check out [`iron-selector`'s `behaviors` branch](https://github.com/PolymerElements/iron-selector/pull/2)
* Run `test/template-repeat.html`, I'd just focus on the `'supports repeated items'` test.

Notice that:
* After [setting the `items`](https://github.com/PolymerElements/iron-selector/blob/d8ef78c4a4142a864228a6c01a117bed842182e7/test/template-repeat.html#L56), the template properly debounces and calls `render`.
* Inside `render`, it is properly calling `_insertRow` -> `_generateRow` -> `stamp`
* The result of a `stamp` is a completely busted row (missing node/fragment, no children)

**Comment by notwaldorf** [comment] 2016-01-26 23:57
This is caused by https://github.com/webcomponents/webcomponentsjs/issues/362, and will be fixed when that's fixed.

**Closed by notwaldorf** 2016-01-26 23:57 UTC
Labels: bug, needs move
